// <auto-generated />
using System;
using CarControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarControl.Migrations
{
    [DbContext(typeof(CarControlContext))]
    [Migration("20200430232950_TblModelo")]
    partial class TblModelo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CarControl.Models.AnoModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<int>("ModeloId");

                    b.Property<int>("VeiculoId");

                    b.Property<Guid?>("VeiculoId1");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("VeiculoId1");

                    b.ToTable("AnoModelo");
                });

            modelBuilder.Entity("CarControl.Models.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int>("Prioridade");

                    b.Property<string>("Site");

                    b.HasKey("Id");

                    b.ToTable("Fabricante");
                });

            modelBuilder.Entity("CarControl.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FabricanteId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("CarControl.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AnoFab");

                    b.Property<int>("AnoModeloId");

                    b.Property<string>("Chassis");

                    b.Property<string>("Cor");

                    b.Property<int?>("FabricanteId");

                    b.Property<int>("Hodometro");

                    b.Property<string>("Origem");

                    b.Property<string>("Placa");

                    b.Property<int>("Renavam");

                    b.Property<double>("ValorPago");

                    b.Property<double>("ValorVenda");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("CarControl.Models.AnoModelo", b =>
                {
                    b.HasOne("CarControl.Models.Modelo", "Modelo")
                        .WithMany("AnoModelos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarControl.Models.Veiculo", "Veiculo")
                        .WithMany("AnoModelo")
                        .HasForeignKey("VeiculoId1");
                });

            modelBuilder.Entity("CarControl.Models.Modelo", b =>
                {
                    b.HasOne("CarControl.Models.Fabricante", "Fabricante")
                        .WithMany("Modelo")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CarControl.Models.Veiculo", b =>
                {
                    b.HasOne("CarControl.Models.Fabricante", "Fabricante")
                        .WithMany()
                        .HasForeignKey("FabricanteId");
                });
#pragma warning restore 612, 618
        }
    }
}
